/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1VerifyWebsiteRouteImport } from './routes/api/public/v1/verify/website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1VerifyWebsiteRoute =
  ApiPublicV1VerifyWebsiteRouteImport.update({
    id: '/api/public/v1/verify/website',
    path: '/api/public/v1/verify/website',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/verify/website': typeof ApiPublicV1VerifyWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/verify/website': typeof ApiPublicV1VerifyWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/verify/website': typeof ApiPublicV1VerifyWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/v1/verify/website'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/v1/verify/website'
  id: '__root__' | '/' | '/api/public/v1/verify/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1VerifyWebsiteRoute: typeof ApiPublicV1VerifyWebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/verify/website': {
      id: '/api/public/v1/verify/website'
      path: '/api/public/v1/verify/website'
      fullPath: '/api/public/v1/verify/website'
      preLoaderRoute: typeof ApiPublicV1VerifyWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1VerifyWebsiteRoute: ApiPublicV1VerifyWebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
